app = "fut-whatsapp-bot"
primary_region = "gru"

[build]

[env]
  PORT = "4000"

[[mounts]]
  source = "fut_storage"
  destination = "/app/storage"

[[services]]
  internal_port = 4000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
